//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSqlAzMan.CustomDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class identity_UserValidationRequest
    {
        public string userValRequestId { get; set; }
        public System.DateTime valRequestDate { get; set; }
        public string ldapDomain { get; set; }
        public string userName { get; set; }
        public string clientApplication { get; set; }
        public string azManStore { get; set; }
        public string azManAplication { get; set; }
        public string azManItem { get; set; }
        public Nullable<int> UserID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual identity_User identity_User { get; set; }
    }
}
