//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSqlAzMan.CustomDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class identity_Login
    {
        public string LoginId { get; set; }
        public string AppName { get; set; }
        public string LDAPDomain { get; set; }
        public string UserName { get; set; }
        public string RemoteIpV4 { get; set; }
        public System.DateTime LogIn { get; set; }
        public System.DateTime Expires { get; set; }
        public int Timeout { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public bool Expired { get; set; }
        public Nullable<System.DateTime> LogOff { get; set; }
        public bool LoggedOut { get; set; }
        public bool Renovated { get; set; }
        public Nullable<System.DateTime> Renewal { get; set; }
        public Nullable<int> Expiration_Renewal { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
