//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSqlAzMan.CustomDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity_UserBranchOffice
    {
        public int UserID { get; set; }
        public string BranchOfficeId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual identity_BranchOffice identity_BranchOffice { get; set; }
        public virtual identity_User identity_User { get; set; }
    }
}
