//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzManWinUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Details")]
        public global::AzManWinUI.ListViewTypeEnum ManagerUI_ListViewType {
            get {
                return ((global::AzManWinUI.ListViewTypeEnum)(this["ManagerUI_ListViewType"]));
            }
            set {
                this["ManagerUI_ListViewType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Large")]
        public global::AzManWinUI.TreeNodeSizeEnum ManagerUI_TreeNodeSize {
            get {
                return ((global::AzManWinUI.TreeNodeSizeEnum)(this["ManagerUI_TreeNodeSize"]));
            }
            set {
                this["ManagerUI_TreeNodeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Role")]
        public global::AzManWinUI.AuthorizationViewEnum ManagerUI_AuthorizationView {
            get {
                return ((global::AzManWinUI.AuthorizationViewEnum)(this["ManagerUI_AuthorizationView"]));
            }
            set {
                this["ManagerUI_AuthorizationView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("es")]
        public string ManagerUI_Culture {
            get {
                return ((string)(this["ManagerUI_Culture"]));
            }
            set {
                this["ManagerUI_Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Role")]
        public global::AzManWinUI.StructureViewEnum ManagerUI_StructureView {
            get {
                return ((global::AzManWinUI.StructureViewEnum)(this["ManagerUI_StructureView"]));
            }
            set {
                this["ManagerUI_StructureView"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.22.1.21;Initial Catalog=AzMan;Persist Security Info=True;User ID=" +
            "secman;Password=sisepuede")]
        public string AzManConnectionString {
            get {
                return ((string)(this["AzManConnectionString"]));
            }
        }
    }
}
